# Python CircleCI 2.0 configuration file
version: 2


jobs:

  #trabalho 1:
  Constroi_e_envia_pacote:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo com GitHub
      - checkout

       #Step 2: cria o ambiente virtual e instala as dependencias
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd 2_model_package
            pip install -r requirements.txt

      # Step 3: treina o modelo
      - run:
          name: treina o modelo
          command: |
            . venv/bin/activate
            cd 2_model_package
            python -m modelo.treina_modelo

      # Step 4: constroi o pacote e publica
      - run:
          name: constroi o pacote e publica
          command: |
            . venv/bin/activate
            python -m pip install build twine
            cd 2_model_package
            python -m build
            chmod a+x envio_pacote.sh
            ./envio_pacote.sh


  #trabalho 2:
  baixa_e_testa_modelo_do_servidor:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:

      #Step 1: cria o ambiente virtual
      - run:
          name: cria o ambiente virtual
          command: |
              python3 -m venv venv

      #Step 2: baixa e testa o pacote do servidor
      - run:
          name: download do pacote do gemfury
          command: |
            . venv/bin/activate
            pip install --index-url https://pypi.fury.io/joaogambaro/ --extra-index-url https://pypi.org/simple/ modelo_body_performance

      - run:
          name: testa pacote do servidor
          command: |
            . venv/bin/activate
            python -m teste_modelo.test_previsoes -v


  #trabalho 3
  implementa_API:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:
      #Step 1: baixa o repositório do git
      - checkout

      #Step 2:
      - run:
          name: envia API para o heroku
          command: |
            git subtree push --prefix 3_rest_API https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master




workflows:
  version: 2

 #workflow 1
  contrucao e teste do pacote do servidor:
    jobs:
      - Constroi_e_envia_pacote:
          filters:
            branches:
              only:
                - desenv_package

      - baixa_e_testa_modelo_do_servidor:
          requires:
            - Constroi_e_envia_pacote
          filters:
            branches:
              only:
                - desenv_package


  #workflow 2:
  implementacao da api no heroku:
    jobs:
      - implementa_API:
          filters:
            branches:
              only:
                - master
